variable "short_region" {}
variable "stage" {}
variable "delay_seconds" {}
variable "max_message_size" {}
variable "message_retention_seconds" {}
variable "receive_wait_time_seconds" {}
variable "fifo_queue" {}
variable "content_based_deduplication" {}
variable "queue_service" {}
variable "visibility_timeout_seconds" {}