variable "short_region" {}
variable "stage" {}
variable "iam_role" {}
variable "remote_stage" {}
variable "aws_region" {}
variable "account_code" {}
variable "service_name" {}
variable "queue_arn" {}
variable "runtime" {}
variable "lambda_timeout" {}
variable "lambda_configuration_cache_timeout" {}
variable "lambda_memory_size" {}
